### ISSUE TITLE
Which EXTRA_TOKENS should have matching REPLACEMENTS?

### ISSUE THREAD

**Issue by ranchodeluxe** [akoumjian/datefinder#15]
Issue #14 has highlighted a discrepancy between [extra tokens](https://github.com/akoumjian/datefinder/blob/master/datefinder.py#L22) we use to help us locate dates:

``` python
EXTRA_TOKENS_PATTERN = 'due|by|on|standard|daylight|savings|time|date|of|to|until|z|at|t'
```

and [those tokens](https://github.com/akoumjian/datefinder/blob/master/datefinder.py#L103-L115) which are later replaced because `dateutil.parser` cannot accept them:

``` python
    REPLACEMENTS = {
        "standard": "",
        "daylight": "",
        "savings": "",
        "time": "",
        "date": "",
        "by": "",
        "due": "",
        "on": "",
        ",": "",
    }
```

Currently `'to'` is not in the REPLACEMENTS for example.

My guess is that not all the extra tokens need to be replaced, meaning, REPLACEMENTS is a subset of EXTRA_TOKENS. We should at least have a test that shows which extra tokens dateutil.parse handles and which need to be in REPLACEMENTS.

**Comment by akoumjian** [comment]
We might actually have to add some additional replacements. This was originally designed for dateparser, which handled a few more tokens. I think the only ones that shouldn't get replaced are 'z' and 't', which are just part of regular datetime strings. Technically they are delimiters...

**Comment by akoumjian** [comment]
Okay, so I think all we need to do is add 'to' to the replacements list here. I agree, putting in a test or at least a comment next to `EXTRA_TOKENS_PATTERN` about what's getting replaced would be good for reference.
