### ISSUE TITLE
"On <month_name>" gives a weirdly extracted date value

### ISSUE THREAD

**Issue by khanfarhan10** [akoumjian/datefinder#181]
"text": "12-December-2022 00:00:00",
        "src_string": "on dec",
        "line_idx": 29,
        "span_of_indices": [
          54,
          59
        ]

**Comment by akoumjian** [comment]
Underlying library will fill in today's month day number and year when creating a date from incomplete data. You can adjust this behavior by providing a `base_date` which will be used to fill in missing components.

https://github.com/akoumjian/datefinder/blob/master/datefinder/__init__.py#L24
