### ISSUE TITLE
Parse "next" "last" "upcoming"

### ISSUE THREAD

**Issue by vishwa306** [akoumjian/datefinder#21]
Hey @akoumjian,

Could you add "next", "last", "upcoming" and "this" to the parser? Would like to parse things like "this Friday", "next Wednesday", "Yesterday", "Tomorrow" etc.?

**Comment by akoumjian** [comment]
Yes, relative date times are on the to do list. Should be an existing
ticket.

**Comment by akoumjian** [comment]
Added #170 to track this feature request for next release.
