### ISSUE TITLE
Minutes / Months 

### ISSUE THREAD

**Issue by virgodi** [akoumjian/datefinder#22]
Hi !

I just wanted to start by thanking you for datefinder, exactly what I was looking.

I think I found a small bug but couldn't understand how to fix it in the source code.

When parsing strings such as:

`>>> list(datefinder.find_dates('2 months'))[0]`

it parses months as minutes, i.e. : 

`datetime.datetime(2016, 6, 10, 8, 31, 41, 469126)`

If you could have a look at it, it'd be great ! Thanks a lot again !

**Comment by akoumjian** [comment]
I will take a look! This may be an issue with the underlying date parser.

**Comment by akoumjian** [comment]
Looking back at this, it looks like you are trying to capture spans of time, rather than specific dates. I'll be tracking this as #171
