### ISSUE TITLE
wrong interpretation

### ISSUE THREAD

**Issue by aushev** [akoumjian/datefinder#24]
I have the following string:
`str1= 'SvrCk: 21     3:13p 04/19/16 Separate checks: 8-of-8'`
the date I want to extract will be obviously 2016-04-19 (or, in full, 2016-04-19 15:13 - but I don't even need the time). Unfortunately, `datefinder` fails to recognize it:

```
matchesFuzzy = datefinder.find_dates(str1)
for match in matchesFuzzy: print(match)
```

gives this:

> 2016-08-21 03:13:00
> 2016-09-04 00:00:00
> 2016-08-08 00:00:00

and

```
matchesStrict = datefinder.find_dates(str1, strict=True)
for match in matchesStrict: print(match)
```

gives this:

> 2016-09-04 00:00:00

**Comment by akoumjian** [comment]
Hm, I feel like strict mode should be finding this.

**Comment by aushev** [comment]
yes, I thought so - but it doesn't :(
I tried on both Python2 and Python3 - it always finds 2016-09-04 instead of 2016-04-19, I don't understand why...

**Comment by akoumjian** [comment]
This was a funny one. It was pulling in the `Sep` from `Separate` and then, considering it part of a valid date string sends this in to dateutil: `04/19/16 Sep`. Dateutil didn't like the extra information and basically rejected it. 

I updated the month abbreviation regexes to require either a period `\.` or whitespace `\s`, so avoid the strings being part of some other token.
