### ISSUE TITLE
Parse range of dates

### ISSUE THREAD

**Issue by dpmontero** [akoumjian/datefinder#26]
Find dates ranges, for example:

> 17 and 18 september 2016
> 
> from 7 to 14 of september 2016
> 
> from friday 2 of september to saturday 10 of 2016
> 
> september, from 7 to 10
> 
> from 31 august to 2 of september 2016

In spanish is typical:

> del 17 al 20 de septiembre 2016
> 
> del 31 de agosto al 2 de septiembre 2016

Good job!!
Thanks!

**Comment by akoumjian** [comment]
Tracking as #171
