### ISSUE TITLE
Month abbreviation with period fails

### ISSUE THREAD

**Issue by jwaynes** [akoumjian/datefinder#35]
Using Python 3.5.2 and datefinder 0.6.0.
textstring = "Oct. , 1881"
find_dates returns no matches.  
If the period following "Oct" is removed, then find_dates returns a match.

Periods after date abbreviations is quite common.  I would have expected this to work.

**Comment by akoumjian** [comment]
If you install from git master does this still happen?

**Comment by jwaynes** [comment]
I have not tried installing from GitHub.  
I've chosen to simply strip the '.' and continue processing.

**Comment by markgalassi** [comment]
This is still a problem with 0.6.1 as installed by pip3.  My string that reproduces it is:

'1)  MCW Will, Nov. 5, 1953'  --> 1953-05-09 00:00:00

whereas if you remove the period it works well.

**Comment by TomGoBravo** [comment]
I ran into this problem too and looked at the master code. I found some existing tests for this which were commented out and a simple fix. I don't have much experience with github but think I've made a pull request with my tiny patch. Hope this helps. Thank you for making a handy library.

**Comment by TomGoBravo** [comment]
Pull 41 only partially fixes the issue. I added some more tests to tests/test_find_dates.py. All but one pass with the tiny patch. Looks like [only Sept is commonly abbreviated to 4 letters](http://www.aresearchguide.com/monthdayabb.html) and needs a bit more work.

# Examples from https://github.com/akoumjian/datefinder/issues/35
('Oct. , 1881', datetime(1881, 10, 20)),
('1) MCW Will, Nov. 5, 1953', datetime(1953, 11, 5)),
('Sep. 21, 2006', datetime(2006, 9, 21, 0, 0)),
('Sept. 21, 2006', datetime(2006, 9, 21, 0, 0)),
('text Sep. 21, 2006', datetime(2006, 9, 21, 0, 0)),
('text Sept 21, 2006', datetime(2006, 9, 21, 0, 0)),
('text Sept. 21, 2006', datetime(2006, 9, 21, 0, 0)),  # Fails

**Comment by akoumjian** [comment]
This was fixed.
