### ISSUE TITLE
Dates ending with Z timezone not recognized if there is no millisecond

### ISSUE THREAD

**Issue by rawouter** [akoumjian/datefinder#37]
Let me start with: this is exactly the module I was looking for, thanks a lot!

I'm having an annoying bug however, I have dates ending the with "Z" keyword for the timezone, which is ISO 8601 compliant but the module fails to parse it:

```python
>>> list(datefinder.find_dates('INFO[2017-02-03T09:04:08Z] Done job'))
[]

>>> list(datefinder.find_dates('INFO[2017-02-03T09:04:08] Done job'))
[datetime.datetime(2017, 2, 3, 9, 4, 8)]
```

**Comment by ranchodeluxe** [comment]
@rawouter: nice eye

It looks like the regex parser is expecting a microsecond too. Not sure if the microsecond is a required part of `ISO 8601`. The regex parser might want to be flexible enough for both.

```python
In [1]: import datefinder

In [2]: list(datefinder.find_dates('INFO[2017-02-03T09:04:08.023423Z] Done job'))
Out[2]: [datetime.datetime(2017, 2, 3, 9, 4, 8)]
```

**Comment by rawouter** [comment]
Thanks for your fast reply, I'm not an ISO 8601 pro so I'll leave it up to you, but indeed if the parser can be flexible enough that would be great ;-)

Talking about microsecond, I'm dealing with very nasty all kind of logs; these also fail I can also open an other issue if you want:

```
>>> list(datefinder.find_dates('[2017-02-03 07:52:36.958]', source=True))
[(datetime.datetime(2017, 2, 3, 7, 52, 36), '2017-02-03 07:52:36')]
```
--> missing the .958

**Comment by ranchodeluxe** [comment]
thanks, that's good to know also

**Comment by rawouter** [comment]
Proposing a fix for issues I discovered, please have a look at https://github.com/akoumjian/datefinder/pull/38 for more details.

Thanks!
