### ISSUE TITLE
Enable to pass arguments dayfirst and yearfirst

### ISSUE THREAD

**Issue by soumendrak** [akoumjian/datefinder#42]
In the `dateutil` module, there is option to customize to take day as first or year as first.
For example
Input: 11-12-2017 with `dayfirst=True`
Output: 11-DEC-2017 in DD-MMM-YYYY

Input: 11-12-2017 with `dayfirst=False` (default)
Output: 12-NOV-2017.

Please enable this argument to be passed from `datefinder`.

**Comment by akoumjian** [comment]
This is addressed as the new `first` parameter. Thank you!
