### ISSUE TITLE
Day format not parsed

### ISSUE THREAD

**Issue by mlberlin** [akoumjian/datefinder#63]
A day specified as in _12th day of December, 2001_ or in regex geek:

`[0-9][0-9]?(st|nd|rd|th) day of`

is not parsed.

Thnx for the great work!

**Comment by jsenecal** [comment]
I have a fix for that :) https://github.com/connectitnet/datefinder/commit/bb822249d5b18ab9f48c2a34d3001419bcd4c53d

**Comment by akoumjian** [comment]
@jsenecal I like the progress. Any interest in setting up a PR so we can discuss?

**Comment by jsenecal** [comment]
@akoumjian Of course! I thought that since most issues were left unresolved this project lacked an active maintainer - I'll work on cherry-picking changes I've made in a PR

**Comment by akoumjian** [comment]
I have been completely absent, much to my dismay. However, I was able to glance at your fork and like a lot of the changes so I would be happy to review a PR. I have been meaning to refactor this project for a while but life events have resulted in having a lot less free time for projects like this one.

Thanks!
