### ISSUE TITLE
Non-date (year) being interpreted as a date (year)

### ISSUE THREAD

**Issue by DavidRDoyle** [akoumjian/datefinder#75]
Hi, 
Datefinder is great - thank you. 
Could you take a look at the text in the data variable below and suggest why 6277 is being interpreted as a year while 9255 and 6010 are not (correctly) being interpreted as years?

`import datefinder
data = "Your appointment is on July 14th, 2016. Your bill is due 05/05/2016 at 5:30pm. Operated by Reader Offers Ltd (ABTA F9255 & W6277, ATOL 6010) trading as ROL Cruise."
matches = datefinder.find_dates(data)
for match in matches:
    print(match)`

Results:
2016-07-14 00:00:00
2016-05-05 17:30:00
6277-04-30 00:00:00

Thank you

**Comment by sathk882** [comment]
HI, I am also facing the same issue. Did you find any solution?
