### ISSUE TITLE
Cannot find date in a particular type sentences

### ISSUE THREAD

**Issue by maad-boy** [akoumjian/datefinder#96]
1) 'Dutta is the recipient of Femina Miss India Universe title in 2004.' => cannot find 2004
2) 'she said that she hit depression after being traumatized on the sets of "Horn OK" in 2008.' => cannot find 2008

**Comment by jsenecal** [comment]
Could you try my fork? I added tests and made changes that could address your use case. https://github.com/connectitnet/datefinder/blob/master/tests/test_find_dates.py#L58-L59
